openapi: 3.1.0
info:
    $ref: './shared/info.yaml'
servers:
    - url: meet/internal-api/v1
      description: OpenVidu Meet Internal API
tags:
    $ref: './shared/tags.yaml'

paths:
    /auth/login:
        $ref: './auth/auth.yaml#/~1auth~1login'
    /auth/logout:
        $ref: './auth/auth.yaml#/~1auth~1logout'
    /auth/refresh:
        $ref: './auth/auth.yaml#/~1auth~1refresh'
    /api-keys:
        $ref: './api-keys/api-keys.yaml#/~1auth~1api-keys'
    /users/me:
        $ref: './users/internal/users.yaml#/~1users~1me'
    /users/change-password:
        $ref: './users/internal/users.yaml#/~1users~1change-password'
    # /config/security:
    #     $ref: './config/config.yaml#/~1config~1security'
    /config/rooms/appearance:
        $ref: './config/config.yaml#/~1config~1rooms~1appearance'
    /config/captions:
        $ref: './config/config.yaml#/~1config~1captions'
    /config/meeting-layout:
        $ref: './config/config.yaml#/~1config~1meeting-layout'
    /rooms/{roomId}/members/token:
        $ref: './room-members/internal/room-members.yaml#/~1rooms~1{roomId}~1members~1token'
    /rooms/{roomId}/members/token/refresh:
        $ref: './room-members/internal/room-members.yaml#/~1rooms~1{roomId}~1members~1token~1refresh'
    /ai/assistants:
        $ref: './ai-assistants/ai-assistants.yaml#/~1ai~1assistants'
    /ai/assistants/{assistantId}:
        $ref: './ai-assistants/ai-assistants.yaml#/~1ai~1assistants~1{assistantId}'
    /analytics:
        $ref: './analytics/analytics.yaml#/~1analytics'

components:
    securitySchemes:
        $ref: ./shared/security.yaml
    schemas:
        MeetApiKey:
            $ref: ./api-keys/schemas/meet-api-key.yaml
        MeetUser:
            $ref: ./users/schemas/meet-user.yaml
        SecurityConfig:
            $ref: ./config/schemas/global-security-config.yaml
        RoomsAppearanceConfig:
            $ref: ./config/schemas/rooms-appearance-config.yaml
        MeetRoom:
            $ref: ./rooms/schemas/meet-room.yaml
        MeetAnalytics:
            $ref: ./analytics/schemas/meet-analytics.yaml
        AiAssistant:
            $ref: ./ai-assistants/schemas/ai-assistant.yaml
        Error:
            $ref: ./shared/schemas/error.yaml
